/**
 * SAMPLE PROJECT DATASET (INDEPENDENT / NON-POLAR-1 DEMO DATA)
 * ============================================================
 * Used exclusively for testing the portability of the AI Assistant system.
 * Contains completely different stations, missions, personnel, cargo,
 * inventory, and emergency records located in the Greenland / High Arctic corridor.
 */

export const sampleProjectData = {
  projectName: 'ARCTIC POLAR II',
  locations: [
    {
      id: 'LOC-AURORA',
      name: 'Aurora Research Station',
      type: 'STATION',
      region: 'Greenland Ice Sheet Summit',
      latitude: 72.5833,
      longitude: -38.4500,
      capacity: 35,
      notes: 'Year-round atmospheric baseline and deep ice-core drilling facility at 3,200m elevation.',
    },
    {
      id: 'LOC-BOREALIS',
      name: 'Borealis Field Camp',
      type: 'CAMP',
      region: 'North-East Greenland National Park',
      latitude: 76.7667,
      longitude: -18.6667,
      capacity: 14,
      notes: 'Seasonal glaciology traverse staging camp supporting robotic ice radar probes.',
    },
    {
      id: 'LOC-NORDIC',
      name: 'Nordic Logistics Depot',
      type: 'PORT',
      region: 'Svalbard Coastal Corridor',
      latitude: 78.2200,
      longitude: 15.6500,
      capacity: 60,
      notes: 'Maritime cargo consolidation terminal and LC-130 skiway staging apron.',
    },
  ],

  expeditions: [
    {
      id: 'EXP-801',
      name: 'Permafrost Methane Coring',
      destination: 'Aurora Research Station',
      location_id: 'LOC-AURORA',
      start_date: '2026-05-01',
      end_date: '2027-05-15',
      team_size: 12,
      status: 'ACTIVE',
      progress: 84,
      leader: 'Dr. Sarah Lindqvist',
      objective: 'Drilling 800m deep firn-air cores to quantify sub-ice methane clathrate venting.',
    },
    {
      id: 'EXP-802',
      name: 'Greenland Ice Sheet Velocity Survey',
      destination: 'Borealis Field Camp',
      location_id: 'LOC-BOREALIS',
      start_date: '2026-08-10',
      end_date: '2027-11-30',
      team_size: 24,
      status: 'ACTIVE',
      progress: 29,
      leader: 'Capt. Erik Thorne',
      objective: 'Autonomous ground-penetrating radar traverse tracking basal sliding velocity.',
    },
    {
      id: 'EXP-803',
      name: 'Arctic Maritime Aerosol Sampling',
      destination: 'Nordic Logistics Depot',
      location_id: 'LOC-NORDIC',
      start_date: '2025-09-01',
      end_date: '2026-04-20',
      team_size: 8,
      status: 'COMPLETED',
      progress: 100,
      leader: 'Dr. Kenji Sato',
      objective: 'High-latitude black carbon and marine boundary layer condensation monitoring.',
    },
  ],

  personnel: [
    {
      id: 'P-101',
      name: 'Dr. Sarah Lindqvist',
      role: 'Lead Paleoclimatologist',
      status: 'ACTIVE',
      is_active: true,
      location_id: 'LOC-AURORA',
      expedition_id: 'EXP-801',
      latitude: 72.5833,
      longitude: -38.4500,
      blood_group: 'O+',
      satphone: '+881-690-112-901',
      last_active: '2026-09-11T09:15:00Z',
    },
    {
      id: 'P-102',
      name: 'Capt. Erik Thorne',
      role: 'Polar Traverse Commander',
      status: 'ACTIVE',
      is_active: true,
      location_id: 'LOC-BOREALIS',
      expedition_id: 'EXP-802',
      latitude: 76.7667,
      longitude: -18.6667,
      blood_group: 'B-',
      satphone: '+881-690-112-902',
      last_active: '2026-09-11T08:40:00Z',
    },
    {
      id: 'P-103',
      name: 'Dr. Kenji Sato',
      role: 'Atmospheric Chemist',
      status: 'OFF_DUTY',
      is_active: false,
      location_id: 'LOC-NORDIC',
      expedition_id: 'EXP-803',
      latitude: 78.2200,
      longitude: 15.6500,
      blood_group: 'A+',
      satphone: '+881-690-112-903',
      last_active: '2026-09-10T16:00:00Z',
    },
  ],

  inventory: [
    {
      id: 'I-801',
      item_name: 'Jet-A1 Polar Fuel',
      category: 'Fuel',
      quantity: 28500,
      minimum_quantity: 8000,
      unit: 'litres',
      location: 'Aurora Research Station',
      condition: 'GOOD',
    },
    {
      id: 'I-802',
      item_name: 'High-Altitude Arctic Tents',
      category: 'Safety',
      quantity: 4,
      minimum_quantity: 15,
      unit: 'sets',
      location: 'Borealis Field Camp',
      condition: 'GOOD',
    },
    {
      id: 'I-803',
      item_name: 'Emergency Thermal Rations',
      category: 'Food',
      quantity: 1200,
      minimum_quantity: 400,
      unit: 'packs',
      location: 'Nordic Logistics Depot',
      condition: 'NEW',
    },
  ],

  cargo: [
    {
      id: 'CRG-901',
      item_name: 'Deep Core Drill Bit Assembly',
      quantity: 2,
      unit: 'crates',
      weight_kg: 420,
      priority: 'HIGH',
      status: 'DELAYED',
      location: 'Nordic Logistics Depot',
      destination: 'Aurora Research Station',
      eta: '2026-09-20',
    },
    {
      id: 'CRG-902',
      item_name: 'Solar-Assisted Battery Banks',
      quantity: 6,
      unit: 'units',
      weight_kg: 780,
      priority: 'MEDIUM',
      status: 'IN_TRANSIT',
      location: 'Greenland Inland Traverse',
      destination: 'Borealis Field Camp',
      eta: '2026-09-15',
    },
  ],

  emergencies: [
    {
      id: 'INC-801',
      type: 'EQUIPMENT',
      location: 'Borealis Generator Shelter Sector 1',
      location_id: 'LOC-BOREALIS',
      latitude: 76.7667,
      longitude: -18.6667,
      severity: 'CRITICAL',
      description: 'Primary diesel generator cylinder head blown, camp running on backup battery reserves.',
      status: 'ACTIVE',
      reported_at: '2026-09-11T07:20:00Z',
      assigned_team: 'Borealis Rapid Engineering Unit',
    },
  ],

  weather: {
    'LOC-AURORA': {
      temperature: -24.5,
      windSpeed: 42,
      windGusts: 65,
      windChill: -38,
      weatherCode: 73,
      condition: 'Moderate snow',
    },
    'LOC-BOREALIS': {
      temperature: -18.2,
      windSpeed: 28,
      windGusts: 38,
      windChill: -28,
      weatherCode: 3,
      condition: 'Overcast',
    },
  },
}
